/**
 * APPROVAL SERVICE — Human review before publishing
 * 
 * How it works:
 *  1. Content is generated by AI
 *  2. Email sent to founder with APPROVE / REJECT links
 *  3. Founder clicks link → post goes live or gets discarded
 *  4. Auto-approve after X hours if no response (configurable)
 *  5. All pending approvals stored in MongoDB
 */

const https   = require('https')
const crypto  = require('crypto')

class ApprovalService {
  constructor() {
    this.enabled      = process.env.REQUIRE_APPROVAL === 'true'
    this.autoApproveAfterHours = parseInt(process.env.AUTO_APPROVE_HOURS || '0') // 0 = never auto-approve
    this.baseUrl      = process.env.ENGINE_URL || `http://localhost:${process.env.ENGINE_PORT || 4000}`
    this.alertEmail   = process.env.ALERT_EMAIL
    this.resendKey    = process.env.RESEND_API_KEY
  }

  // ── Generate a secure token for approve/reject links
  generateToken() {
    return crypto.randomBytes(32).toString('hex')
  }

  // ── Send approval email with preview + approve/reject buttons
  async requestApproval(content, platform, product) {
    if (!this.enabled) return { approved: true, auto: true }

    const { Approval } = require('../models')

    const approveToken = this.generateToken()
    const rejectToken  = this.generateToken()

    // Store in DB
    const approval = await Approval.create({
      platform,
      product,
      content,
      approveToken,
      rejectToken,
      status:    'pending',
      expiresAt: this.autoApproveAfterHours > 0
        ? new Date(Date.now() + this.autoApproveAfterHours * 3600000)
        : null,
    })

    // Send review email
    await this.sendReviewEmail(approval)

    console.log(`📧 [APPROVAL] Review email sent for ${platform} post`)
    console.log(`   Approve: ${this.baseUrl}/api/approval/approve/${approveToken}`)
    console.log(`   Reject:  ${this.baseUrl}/api/approval/reject/${rejectToken}`)

    return { approved: false, pendingId: approval._id, approveToken, rejectToken }
  }

  // ── Wait for approval (polls DB every 30 seconds)
  async waitForApproval(pendingId, timeoutMinutes = 120) {
    const { Approval } = require('../models')
    const timeoutMs = timeoutMinutes * 60 * 1000
    const start     = Date.now()

    return new Promise((resolve) => {
      const check = async () => {
        try {
          const approval = await Approval.findById(pendingId)
          if (!approval) return resolve({ approved: false, reason: 'not_found' })

          if (approval.status === 'approved') return resolve({ approved: true })
          if (approval.status === 'rejected') return resolve({ approved: false, reason: 'rejected' })

          // Auto-approve if expired and auto-approve is enabled
          if (approval.expiresAt && new Date() > approval.expiresAt) {
            await Approval.findByIdAndUpdate(pendingId, { status: 'auto_approved' })
            console.log(`⚡ [APPROVAL] Auto-approved ${approval.platform} post (${this.autoApproveAfterHours}h timeout)`)
            return resolve({ approved: true, auto: true })
          }

          // Timeout
          if (Date.now() - start > timeoutMs) {
            return resolve({ approved: false, reason: 'timeout' })
          }

          setTimeout(check, 30000) // check every 30 seconds
        } catch (err) {
          resolve({ approved: false, reason: err.message })
        }
      }
      check()
    })
  }

  // ── Send the review email via Resend
  async sendReviewEmail(approval) {
    if (!this.resendKey || !this.alertEmail) {
      console.log('⚠ [APPROVAL] No Resend key or email — approval links printed to console only')
      return
    }

    const approveUrl = `${this.baseUrl}/api/approval/approve/${approval.approveToken}`
    const rejectUrl  = `${this.baseUrl}/api/approval/reject/${approval.rejectToken}`

    // Format content preview by platform
    const preview = this.formatPreview(approval.content, approval.platform)

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: -apple-system, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
    .card { background: white; border-radius: 12px; padding: 28px; max-width: 600px; margin: 0 auto; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
    .logo { font-size: 20px; font-weight: 800; color: #7B6CF6; margin-bottom: 4px; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; }
    .badge-li { background: #E7F0F8; color: #0A66C2; }
    .badge-tw { background: #E7F4FD; color: #1DA1F2; }
    .badge-rd { background: #FFF0E8; color: #FF4500; }
    h2 { color: #1a1a2e; font-size: 18px; margin: 16px 0 8px; }
    .preview { background: #f8f8fc; border-left: 3px solid #7B6CF6; border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 16px 0; font-size: 14px; line-height: 1.7; color: #333; white-space: pre-wrap; }
    .preview-label { font-size: 11px; font-weight: 600; letter-spacing: 0.08em; color: #9896AA; margin-bottom: 10px; }
    .actions { display: flex; gap: 12px; margin-top: 24px; }
    .btn { display: inline-block; padding: 13px 28px; border-radius: 8px; font-weight: 600; font-size: 15px; text-decoration: none; text-align: center; }
    .btn-approve { background: #2DCB8F; color: white; flex: 1; }
    .btn-reject  { background: #f5f5f5; color: #666; border: 1px solid #ddd; flex: 1; }
    .meta { font-size: 12px; color: #aaa; margin-top: 20px; padding-top: 16px; border-top: 1px solid #f0f0f0; }
    .tweet { background: #f8f8fc; border: 1px solid #e8e8f0; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px; font-size: 14px; line-height: 1.6; color: #333; }
    .tweet-num { font-size: 11px; color: #9896AA; font-weight: 600; margin-bottom: 5px; }
  </style>
</head>
<body>
<div class="card">
  <div class="logo">Toolify AI</div>
  <div style="font-size:13px;color:#9896AA;">Autonomous Engine — Content Review</div>

  <h2>Review before publishing</h2>
  <p style="color:#666;font-size:14px;">Your AI generated the following content. Approve to publish or reject to discard.</p>

  <div>
    <span class="badge badge-${approval.platform === 'linkedin' ? 'li' : approval.platform === 'twitter' ? 'tw' : 'rd'}">
      ${approval.platform.toUpperCase()}
    </span>
    <span style="font-size:12px;color:#aaa;margin-left:8px;">${approval.product} · ${new Date().toLocaleString('en-IN')}</span>
  </div>

  ${preview}

  <div class="actions">
    <a href="${approveUrl}" class="btn btn-approve">✅ Approve &amp; Publish</a>
    <a href="${rejectUrl}"  class="btn btn-reject">❌ Reject</a>
  </div>

  ${this.autoApproveAfterHours > 0
    ? `<div class="meta">⏰ Auto-approves in ${this.autoApproveAfterHours} hours if no action taken.</div>`
    : `<div class="meta">📌 Will not publish until you approve. No expiry.</div>`
  }

  <div class="meta">
    Or use these links:<br>
    ✅ Approve: <a href="${approveUrl}">${approveUrl}</a><br>
    ❌ Reject: <a href="${rejectUrl}">${rejectUrl}</a>
  </div>
</div>
</body>
</html>`

    const body = JSON.stringify({
      from:    'noreply@sahilsingh.co.in',
      to:      this.alertEmail,
      subject: `[Toolify AI] Review ${approval.platform} post before publishing`,
      html,
    })

    return new Promise((resolve) => {
      const req = https.request({
        hostname: 'api.resend.com',
        path:     '/emails',
        method:   'POST',
        headers:  {
          Authorization:    `Bearer ${this.resendKey}`,
          'Content-Type':   'application/json',
          'Content-Length': Buffer.byteLength(body),
        }
      }, res => {
        let d = ''
        res.on('data', c => d += c)
        res.on('end', () => {
          if (res.statusCode === 200 || res.statusCode === 201) {
            resolve({ sent: true })
          } else {
            console.error(`[APPROVAL EMAIL] Resend error ${res.statusCode}: ${d.slice(0, 100)}`)
            resolve({ sent: false })
          }
        })
      })
      req.on('error', err => { console.error('[APPROVAL EMAIL]', err.message); resolve({ sent: false }) })
      req.write(body)
      req.end()
    })
  }

  // ── Format content preview per platform
  formatPreview(content, platform) {
    if (platform === 'twitter') {
      const tweets = Array.isArray(content) ? content : [content]
      return tweets.map((t, i) => `
        <div class="tweet">
          <div class="tweet-num">Tweet ${i + 1}/${tweets.length}</div>
          ${this.escHtml(t)}
        </div>`).join('')
    }

    if (platform === 'linkedin') {
      const text = typeof content === 'string' ? content : content?.text || JSON.stringify(content)
      return `<div class="preview-label">POST PREVIEW</div>
              <div class="preview">${this.escHtml(text)}</div>`
    }

    if (platform === 'reddit') {
      const title = content?.title || ''
      const body  = content?.body  || ''
      return `<div class="preview-label">r/${content?.subreddit || 'subreddit'} · POST</div>
              <div class="preview"><strong>${this.escHtml(title)}</strong>\n\n${this.escHtml(body.slice(0, 500))}${body.length > 500 ? '...' : ''}</div>`
    }

    return `<div class="preview">${this.escHtml(JSON.stringify(content, null, 2).slice(0, 600))}</div>`
  }

  escHtml(s) {
    return String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>')
  }
}

module.exports = new ApprovalService()
